### ISSUE TITLE
`snapToGridEnabled` needs getter/setter

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#101]
`StateManager.isSnapToGridEnabled` is basically a getter without the fancy syntax, but there is no straightforward setter that I can see.

**Comment by micahwagner** [comment]
Hi Malcolm, I know how to make isSnapToGridEnabled a getter, but I'm a little confused on what the setter should look like. Should I change the toggleSnapToGrid() to be a setter, or should I create a whole new setter function for _snapToGridEnabled?

**Comment by Meorge** [comment]
I think a dedicated setter for `snapToGridEnabled` would make more sense. The `toggleSnapToGrid()` method would be used to flip the value to the opposite of whatever it currently is

**Comment by Meorge** [comment]
Closed by #116
