### ISSUE TITLE
`SerializedAutomaton` class may be named incorrectly

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#103]
Based on https://stackoverflow.com/questions/3316762/what-is-deserialize-and-serialize-in-json, a "serialized automaton" would be a string representation of an automaton, I think, while a "deserialized" one would be an object in the program's memory that the language can parse.

As such, I'm thinking that the class `SerializedAutomaton` should perhaps be renamed to `SerializableAutomaton` or `DeserializedAutomaton`.

**Comment by Meorge** [comment]
We discussed this and decided that `SerializableAutomaton` makes the most sense as the class name to use.

**Comment by noahwagner04** [comment]
Hi Malcolm, after looking at the code more, I think "deserializedAutomaton" or "JSONAutomaton" are better names. This is because naming it "SerializableAutomaton" suggests it will be serialized, but this interface is only used for storing the parsed JSON string of the automaton. I'm leaning more towards "JSONAutomaton" since it is used for the "json" argument of loadAutomaton, which is just equal to JSON.parse(text). Let me know what you think.

**Comment by noahwagner04** [comment]
Also, I'm assuming you also want me to rename SerializedState, SerializedToken, and SerializedTransition. Correct?

**Comment by Meorge** [comment]
@noahwagner04 
> I think "deserializedAutomaton" or "JSONAutomaton" are better names. This is because naming it "SerializableAutomaton" suggests it will be serialized, but this interface is only used for storing the parsed JSON string of the automaton.

I'd thought that it was also used when encoding the automaton into a JSON string, but checking the code I see I was wrong there! That being said, as I'm looking at the code I feel like we might want to go through and fix up the names of things. JSON itself is a file format for serialized data, but we have functions named `toJSON` that are returning JavaScript objects before they've been technically converted to the format. I think the documentation I originally wrote was wrong about this.

Overall, right now my thought is that we should rename the `toJSON` methods to something like `toSerializable`, and have them return objects conforming to their relevant interface (right now those functions don't appear to have a return type specified):
- `StateManager.toSerializable` would return a `SerializableAutomaton`
- `NodeWrapper.toSerializable` would return a `SerializableNode`
- `TokenWrapper.toSerializable` would return a `SerializableToken`
- etc

The word "serializable" is a bit of a mouthful, but I worry a bit that `JSONAutomaton` is technically inaccurate, since it's still an internal JavaScript object and not a string. Maybe `RawAutomaton` (and "raw" in place of "serializable" in other names) would be best?

> Also, I'm assuming you also want me to rename SerializedState, SerializedToken, and SerializedTransition. Correct?

Yes, I think it makes sense to keep all of their names consistent since they are related 🙂

**Comment by noahwagner04** [comment]
Thanks for clearing things up, in hindsight the term "JSON" would be inaccurate. I agree the toJSON functions should also be renamed, and "serializable" is still the best term.

> Maybe RawAutomaton (and "raw" in place of "serializable" in other names) would be best?

I do like how much more concise "raw" is, but it's not as descriptive as "serializable". I'll rename SerializedAutomaton to SerializableAutomaton (and the others) and then create a separate issue to rename the toJSON functions, if that works for you.

**Comment by Meorge** [comment]
Sounds good to me! 🙂

**Comment by Meorge** [comment]
Closed by #115
