### ISSUE TITLE
Cut, copy, and paste functionality

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#105]
Being able to copy (or cut) and paste selected states and transitions between them could be quite helpful for quickly assembling structures with repeated segments.

**Comment by Meorge** [comment]
@donnlaa Assigned! :) 

Please let us know if you end up deciding to not complete the issue so that we can reassign it to someone else.

**Comment by donnlaa** [comment]
Thanks! I will work on this and keep you updated :)

**Comment by donnlaa** [comment]
Update: Already made function to copy paste and cut selected states and transitions between them, now i just need to modify it to work well with undo and redo functions :) i think at weekend it will be ready

**Comment by donnlaa** [comment]
When we pasting the copied states, for example q0 and q1, should we keep names of pasted states q0 and q1 and let user to rename them manually or should we name them straight away q2,q3 ?

**Comment by Meorge** [comment]
For now I think keeping the same names makes the most sense. In theory the user can rename the states anything they want, so I think it might be strange to have the system revert them back to qX.

That being said, if we do go that route, we'll also need to make sure that the GUI displays an error when there are multiple states with the same name. I think that may already be implemented, but we'll have to double-check.

**Comment by donnlaa** [comment]
okay thanks and yes errors in gui are showing up, that works well.

**Comment by Meorge** [comment]
Closed by #110
