### ISSUE TITLE
Delete operation on multiple selected objects is treated as multiple delete operations

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#119]
When several objects are deleted, each of them pushes a "delete object" action to the action stack. This also means that, despite the user deleting them all with a single button press, they must restore each of them one-by-one using the undo button. To keep the forwards-backwards flow the same, all of these deletions should be grouped into a single action.

**Comment by NattBo** [comment]
I'd like to be assigned to this issue please

**Comment by NattBo** [comment]
Approach plan: Currently the statemanager calls deleteAllSelectedObjects which performs iterative individual removeTransition and removeNode calls. I would adjust deleteAllSelectedObjects to function more like the cutSelectedObjects function. It would assume a list of deletions and then push an object action that includes all the nodes deleted onto the undoredomanager.

**Comment by Meorge** [comment]
That sounds like a good approach to me!
