### ISSUE TITLE
Grid background should be modified to be infinitely scrolling

### ISSUE THREAD

**Issue by ryan-ball-360** [AutomatonBuilderGUI/AutomatonBuilderGUI#27]
When scrolling through the canvas, the grid background does not expand beyond the size it originally was for the window. The logic for the grid background should be modified so the grid background continues on the canvas even after the user scrolls through the canvas.

**Comment by ryan-ball-360** [comment]
this is a test

**Comment by Meorge** [comment]
Fixed with #56
