### ISSUE TITLE
Deleting a selection of states actually deletes all the other states

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#52]
The function `StateManager.deleteAllSelectedObjects()` contains a bug that causes the selected states to be kept, and all others deleted, when the Delete key is pressed, instead of the intended behavior (deleting all of the states selected). 

This might be related to/fix #49.

**Comment by thundershield** [comment]
This was indeed related to #49. Both the list of transitions and nodes were being filtered to remove all non-selected objects instead of selected objects. I've inverted the selection criteria to resolve the issue.
