### ISSUE TITLE
Add "confirm close" modal when attempting to close the window

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#55]
Currently, if you have a state diagram drawn up and you attempt to close the window, it will close immediately. This could lead to people losing their work. It might be nice to have a confirmation modal appear, similar to how the [Desmos Graphing Calculator](https://www.desmos.com/calculator) works. (Further in the future, allowing users to save state diagrams somehow might be nice, but may also require developing a backend, so I think it'd be out of scope for now.)

**Comment by ryan-ball-360** [comment]
If we want a way to allow users to save in the modal window, we could put the download JSON button in the confirm close window.

**Comment by Meorge** [comment]
> If we want a way to allow users to save in the modal window, we could put the download JSON button in the confirm close window.

That would be nice if possible! I'm unsure if the built-in JavaScript tools for the "confirm close" modal would support an extra function like a download/save - that would need to be investigated further.

**Comment by Meorge** [comment]
Added with #71
