### ISSUE TITLE
Add "Fit automaton on screen" button

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#61]
Add a button that calculates the bounding rectangle of the automaton, then scrolls and zooms so that the entire automaton is visible on-screen.

**Comment by obimax99** [comment]
I can take this

**Comment by Meorge** [comment]
I wanted to note: PR #149 looks like it implements an algorithm for finding the effective bounding box of the automaton. Determining the proper zoom level and adjusting the canvas scale to match will still be necessary for this issue. You may want to take a look at their implementation and compare it to yours, to see if there is anything one of you may be missing. In the end, though, it probably will make sense to have both that feature and this one use the same underlying function to avoid code duplication.
