### ISSUE TITLE
UI buttons for undo/redo

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#90]
While the undo/redo functionality is implemented, currently the only way to actually undo or redo actions is by using the keyboard shortcuts. Buttons should be added to the UI that move through the action stack as well.

**Comment by donnlaa** [comment]
Hi, i would like to take this one too

**Comment by Meorge** [comment]
> Hi, i would like to take this one too

@donnlaa One of our capstone team members has claimed this issue already; once they have their account linked with the repository they will be assigned. However, if they do not end up completing the issue, I can reassign it to you then! 😄

**Comment by Meorge** [comment]
Closed by #122
