### ISSUE TITLE
Reduce repetition in Toolbox code

### ISSUE THREAD

**Issue by Meorge** [AutomatonBuilderGUI/AutomatonBuilderGUI#98]
The current Toolbox code looks like it may have a fair amount of unnecessary repetition in it, and could probably be simplified a lot by introducing some helper components.

**Comment by micahwagner** [comment]
Hi Malcom, I have a quick question regarding this issue. I've created a helper function that returns a template for creating a button type. Is this similar to what you were thinking?

**Comment by Meorge** [comment]
@micahwagner That sounds good to me! Looking at the current Toolbox.tsx, I see that there's a lot of repeated text for things like the button styling/`className`s; having a helper function that fills most of that in, while still letting us choose things like the fill color, would help clean it up a lot.

**Comment by micahwagner** [comment]
Sounds good! just submitted a PR doing exactly that, let me know what you think!

**Comment by Meorge** [comment]
Closed by #126
